spring:
  r2dbc:
    url: r2dbc:h2:mem:///test
    username: sa
    password:
  webflux:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
server:
  port: 8081